title = 'Mc2d'

scaling = 1.6
max_stack_size = 64

[window_size]
x = 1280
y = 720
fullscreen = false

[viewport]
top = 100
bottom = 50
left = 500
right = 500

[world]
chunk_size_x = 8
chunk_size_y = 8
