title = 'Mc2d'

scaling = 1.6
max_stack_size = 64

[window_size]
x = 1280
y = 720
fullscreen = false

[viewport]
top = 300
bottom = 200
left = 500
right = 500

[world]
chunk_size_x = 32
chunk_size_y = 32
